apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/controllers
  sourceRef:
    kind: GitRepository
    name: k8s-apps
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/configs
  sourceRef:
    kind: GitRepository
    name: k8s-apps
  prune: true
  wait: true
  dependsOn:
    - name: infra-controllers