apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy
spec:
  interval: 12h
  chart:
    spec:
      chart: gateway-helm
      version: 'v0.0.0-latest'
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: envoy
  releaseName: envoy-gateway
  driftDetection:
    mode: enabled
  values:
    deployment:
      annotations:
        reloader.stakater.com/auto: "true"
        reloader.stakater.com/rollout-strategy: "restart"