apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: client-cache-auth
  namespace: vault
  labels:
    cacheStorageEncryption: "true"
spec:
  vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: vault-secrets-operator-controller-manager
    audiences:
      - vault
  storageEncryption:
    mount: transit
    keyName: vso-client-cache