apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 12h
  chart:
    spec:
      chart: reloader
      version: "2.2.7"
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: reloader
  releaseName: reloader
  driftDetection:
    mode: enabled
  values:
    reloader:
      reloadOnCreate: true
      syncAfterRestart: true
      deployment:
        resources:
          limits:
            memory: "128Mi"
          requests:
            cpu: "25m"
            memory: "64Mi"