apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: influxdb
spec:
  duration: 720h # 30 days
  renewBefore: 168h # 7 days
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  commonName: influxdb-influxdb2.influxdb.svc.cluster.local
  dnsNames:
    - influxdb-influxdb2
    - influxdb-influxdb2.influxdb
    - influxdb-influxdb2.influxdb.svc
    - influxdb-influxdb2.influxdb.svc.cluster.local