apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: influxdb
spec:
  interval: 12h
  chart:
    spec:
      chart: influxdb2
      version: "2.1.2"
      sourceRef:
        kind: HelmRepository
        name: influxdb
        namespace: influxdb
  releaseName: influxdb
  driftDetection:
    mode: enabled
  values:
    image:
      tag: 2.7.11-alpine
    service:
      type: LoadBalancer
      port: 8086
    serviceAccount:
      name: influxdb
    adminUser:
      existingSecret: influxdb-auth
      organization: homelab
      bucket: data
      retention_policy: 1d
    env:
      - name: INFLUXD_TLS_CERT
        value: "/etc/ssl/tls.crt"
      - name: INFLUXD_TLS_KEY
        value: "/etc/ssl/tls.key"
    volumes:
      - name: influxdb2-tls
        secret:
          secretName: influxdb-tls
    mountPoints:
      - name: influxdb2-tls
        mountPath: /etc/ssl
        readOnly: true
    podAnnotations:
      reloader.stakater.com/auto: "true"
      reloader.stakater.com/rollout-strategy: "restart"
    persistence:
      size: 20Gi
    resources:
      limits:
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    livenessProbe:
      scheme: "HTTPS"
    readinessProbe:
      scheme: "HTTPS"