apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 12h
  chart:
    spec:
      chart: cert-manager
      version: 'v1.19.2'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  releaseName: cert-manager
  driftDetection:
    mode: enabled
  values:
    crds:
      enabled: true
    config:
      kind: ControllerConfiguration
      apiVersion: controller.config.cert-manager.io/v1alpha1
      enableGatewayAPI: true