apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 12h
  chart:
    spec:
      chart: cert-manager
      version: 'v1.19.2'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  releaseName: cert-manager
  driftDetection:
    mode: enabled
  values:
    enableCertificateOwnerRef: true # Allows secret delete when Certificate is deleted
    crds:
      enabled: true
    config:
      kind: ControllerConfiguration
      apiVersion: controller.config.cert-manager.io/v1alpha1
      enableGatewayAPI: true
    resources:
      limits:
        memory: "256Mi" 
      requests:
        cpu: "50m"
        memory: "128Mi"
    webhook:
      resources:
        limits:
          memory: "128Mi" 
        requests:
          cpu: "25m"
          memory: "64Mi"
    cainjector:
      resources:
        limits:
          memory: "128Mi" 
        requests:
          cpu: "25m"
          memory: "64Mi"