apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    # Injects Vault server CA with Trust Manager to verify Vault when issuing certs
    vault-server-ca-inject: "true" 
---
apiVersion: v1
kind: Namespace
metadata:
  name: trust-manager