apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: trust-manager
spec:
  interval: 12h
  chart:
    spec:
      chart: trust-manager
      version: 'v0.20.3'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  releaseName: trust-manager
  driftDetection:
    mode: enabled
  values:
    secretTargets:
      enabled: true
      authorizedSecrets:
        # required because Issuer spec only allows secrets to be used to verify Vault server
        - vault-server-ca 
    app:
      trust:
        namespace: trust-manager
      logFormat: json
    resources:
      limits:
        memory: "128Mi" 
      requests:
        cpu: "50m"
        memory: "64Mi"