apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  interval: 12h
  chart:
    spec:
      chart: trust-manager
      version: 'v0.20.3'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  releaseName: trust-manager
  driftDetection:
    mode: enabled
  values:
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi" 
      requests:
        cpu: "50m"
        memory: "32Mi"