apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 12h
  chart:
    spec:
      chart: vault
      version: "0.31.0"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
  releaseName: vault
  driftDetection:
    mode: enabled
  values:
    global:
      tlsDisable: false
    ui:
      enabled: true
    injector:
      enabled: false
    csi:
      enabled: true
      agent:
        enabled: false
      daemonSet:
        securityContext:
          pod:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            privileged: false
            seccompProfile:
              type: RuntimeDefault
          container:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            privileged: false
            seccompProfile:
              type: RuntimeDefault
      extraArgs:
        - -vault-addr="https://vault.vault.svc.cluster.local:8200"
        - -vault-tls-server-name=vault.vault
        - -vault-tls-ca-cert=/etc/ssl/certs/ca.crt
      volumeMounts:
        - name: vault-ca
          mountPath: /etc/ssl/certs/ca.crt
          subPath: ca.crt
          readOnly: true
      volumes:
        - name: vault-ca
          secret:
            secretName: vault-ca
    server:
      service:
        type: LoadBalancer
      extraEnvironmentVars:
        VAULT_CACERT: /vault/userconfig/vault-server-tls/vault.ca
      volumes:
        - name: userconfig-vault-server-tls
          secret:
            defaultMode: 420
            secretName: vault-server-tls
      volumeMounts:
        - mountPath: /vault/userconfig/vault-server-tls
          name: userconfig-vault-server-tls
          readOnly: true
      standalone:
        enabled: true
        config: |
          ui = true 
          
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
            tls_key_file  = "/vault/userconfig/vault-server-tls/vault.key"
            tls_disable_client_certs = true
          }

          storage "file" {
            path = "/vault/data"
          }
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi" 
        requests:
          cpu: "50m"
          memory: "64Mi"