apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault
spec:
  interval: 12h
  chart:
    spec:
      chart: vault-secrets-operator
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
  releaseName: vault-secrets-operator
  targetNamespace: vault
  driftDetection:
    mode: enabled
  values:
    defaultVaultConnection:
      enabled: true
      address: "https://vault.vault.svc.cluster.local:8200"
      caCertSecret: vault-server-ca
      tlsServerName: vault
    controller:
      manager:
        clientCache:
          persistenceModel: direct-encrypted
          storageEncryption:
            enabled: true
            namespace: vault
            keyName: vso-client-cache
            transitMount: transit
            kubernetes:
              role: vault-secrets-operator
              serviceAccount: vault-secrets-operator-controller-manager
              tokenAudiences: ["vault"]
        globalTransformationOptions:
          excludeRaw: true