apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 12h
  chart:
    spec:
      chart: vault
      version: "0.32.0"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
  releaseName: vault
  driftDetection:
    mode: enabled
  values:
    global:
      tlsDisable: false
    ui:
      enabled: true
    server:
      service:
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: 192.168.8.60
      extraEnvironmentVars:
        VAULT_CACERT: /vault/userconfig/vault-server-tls/vault.ca
      volumes:
        - name: userconfig-vault-server-tls
          secret:
            defaultMode: 420
            secretName: vault-server-tls
      volumeMounts:
        - mountPath: /vault/userconfig/vault-server-tls
          name: userconfig-vault-server-tls
          readOnly: true
      standalone:
        enabled: true
        config: |
          ui = true 
          api_addr = "https://vault.homelab:8200"

          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
            tls_key_file  = "/vault/userconfig/vault-server-tls/vault.key"
            tls_disable_client_certs = true
          }

          storage "file" {
            path = "/vault/data"
          }

          telemetry {
            disable_hostname = true
            usage_gauge_period = "1m"
            statsd_address = "vector.vector.svc.cluster.local:9000"
          }
      resources:
        limits:
          memory: "512Mi" 
        requests:
          cpu: "50m"
          memory: "256Mi"