apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 12h
  chart:
    spec:
      chart: kyverno
      version: 'v3.6.1'
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
  releaseName: kyverno
  driftDetection:
    mode: enabled
  values:
    features:
      logging:
        format: json
        verbosity: 2