apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: envoy
spec:
  type: "oci"
  interval: 15m
  url: oci://docker.io/envoyproxy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy
spec:
  interval: 15m
  chart:
    spec:
      chart: gateway-helm
      version: 'v0.0.0-latest'
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: envoy
  releaseName: envoy-gateway
  driftDetection:
    mode: enabled