apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: influxdb
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: influxdb
    serviceAccount: influxdb
    audiences:
      - vault://influxdb/influxdb
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: influxdb-auth
spec:
  type: kv-v2
  mount: kv
  path: influxdb/influxdb/auth
  destination:
    name: influxdb-auth
    create: true
  refreshAfter: 30s
  vaultAuthRef: influxdb