{
 "title": "Cluster Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "influxdb", "query": "influxdb" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"node_name\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Load (1m)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/$E", "type": "math" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_node]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node::tag" ], "type": "tag" }
     ],
     "measurement": "thermal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "node::tag", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_node_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "host.uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "node_name::tag", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "System Load (1m)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$E", "type": "math" }
   ]
  },
  {
   "title": "Host Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "[[tag_node_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "host.memory_used_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "node_name::tag", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "[[tag_node]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "thermal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "node::tag", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "[[tag_node_name]] Rcv",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "node_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "host.network_receive_bytes_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "node_name::tag", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_node_name]] Send",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "node_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "host.network_transmit_bytes_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "node_name::tag", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "[[tag_node_name]] Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host.disk_read_bytes_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "node_name::tag", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_node_name]] Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host.disk_written_bytes_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "node_name::tag", "operator": "=~", "value": "/^$roles$/" }
     ]
    }
   ]
  }
 ]
}