{
 "title": "Data Pipeline",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "influxdb", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Message Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sink Utilisation",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_component_id]]",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "component_id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vector.utilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component_kind::tag", "operator": "=", "value": "sink" }
     ]
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_component_id]]",
     "groupBy": [
      { "params": [ "component_id::tag" ], "type": "tag" }
     ],
     "measurement": "vector.component_sent_events_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "component_kind::tag", "operator": "=", "value": "sink" }
     ]
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": " Output",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vector.component_sent_events_total",
     "query": "SELECT sum(\"value\") / 5 FROM \"vector.component_sent_events_total\" WHERE (\"component_id\"::tag = 'influxdb') AND $timeFilter GROUP BY time(1s) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / -10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "component_kind::tag", "operator": "=", "value": "sink" }
     ]
    },
    {
     "alias": "Input",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vector.component_sent_events_total",
     "query": "SELECT sum(\"value\") / 5 FROM \"vector.component_sent_events_total\" WHERE (\"component_id\"::tag = 'influxdb') AND $timeFilter GROUP BY time(1s) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "component_kind::tag", "operator": "=", "value": "source" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_component_id]]",
     "groupBy": [
      { "params": [ "component_id::tag" ], "type": "tag" }
     ],
     "measurement": "vector.component_errors_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Message Rate by Source",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "[[tag_component_id]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "component_id::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vector.component_sent_events_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "component_kind::tag", "operator": "=", "value": "source" }
     ]
    }
   ]
  },
  {
   "title": "Message Rate Share by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vector.component_sent_events_total",
     "query": "SELECT sum(\"value\")  / 30 FROM \"vector.component_sent_events_total\" WHERE (\"component_id\"::tag = 'docker_logs' OR \"component_id\"::tag = 'logs' OR \"component_id\"::tag = 'metrics') AND $timeFilter GROUP BY time(30s), \"host\"::tag fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "component_kind::tag", "operator": "=", "value": "sink" }
     ]
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Sink Utilisation",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_component_id]]",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "component_id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vector.utilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component_kind::tag", "operator": "=", "value": "sink" }
     ]
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_component_id]]",
     "groupBy": [
      { "params": [ "component_id::tag" ], "type": "tag" }
     ],
     "measurement": "vector.component_sent_bytes_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "component_kind::tag", "operator": "=", "value": "sink" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": " Output",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vector.component_sent_bytes_total",
     "query": "SELECT sum(\"value\") / 5 FROM \"vector.component_sent_events_total\" WHERE (\"component_id\"::tag = 'influxdb') AND $timeFilter GROUP BY time(1s) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / -10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "component_kind::tag", "operator": "=", "value": "sink" }
     ]
    },
    {
     "alias": "Input",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vector.component_received_bytes_total",
     "query": "SELECT sum(\"value\") / 5 FROM \"vector.component_sent_events_total\" WHERE (\"component_id\"::tag = 'influxdb') AND $timeFilter GROUP BY time(1s) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "component_kind::tag", "operator": "=", "value": "source" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_component_id]]",
     "groupBy": [
      { "params": [ "component_id::tag" ], "type": "tag" }
     ],
     "measurement": "vector.component_errors_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput by Source",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "[[tag_component_id]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "component_id::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vector.component_received_event_bytes_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "OR", "key": "component_kind::tag", "operator": "=", "value": "source" }
     ]
    }
   ]
  },
  {
   "title": "Throughput Share by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vector.component_sent_events_total",
     "query": "SELECT sum(\"value\")  / 30 FROM \"vector.component_sent_events_total\" WHERE (\"component_id\"::tag = 'docker_logs' OR \"component_id\"::tag = 'logs' OR \"component_id\"::tag = 'metrics') AND $timeFilter GROUP BY time(30s), \"host\"::tag fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "component_kind::tag", "operator": "=", "value": "sink" }
     ]
    }
   ]
  }
 ]
}