apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki-int/sign/vault-cluster-issuer
    server: https://vault.vault.svc.cluster.local:8200
    serverName: vault.vault
    caBundleSecretRef:
      key: ca.crt
      name: vault-ca
    auth:
      kubernetes:
        role: vault-cluster-issuer
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: vault-issuer