apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: trust-manager
    serviceAccount: trust-manager
    audiences:
      - vault://cert-manager/trust-manager
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: trust-manager-ca-bundle
  namespace: cert-manager
spec:
  type: kv-v2
  mount: kv
  path: cert-manager/trust-manager/ca-bundle
  destination:
    name: vault-issuer-ca
    create: true
  refreshAfter: 30s
  vaultAuthRef: trust-manager