apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  interval: 15m
  chart:
    spec:
      chart: trust-manager
      version: 'v0.20.3'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  releaseName: trust-manager
  driftDetection:
    mode: enabled