apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-host-observer
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - namespaces
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-host-observer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-host-observer
subjects:
  - kind: ServiceAccount
    name: vector
    namespace: vector