apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector
  annotations:
    reloader.stakater.com/auto: "true"
    reloader.stakater.com/rollout-strategy: "restart"
spec:
  template:
    spec:
      serviceAccountName: vector
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 0 # required to read /var/log/pods
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: vector
          image: timberio/vector:latest-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 8222
          envFrom:
            - secretRef:
                name: influxdb-write-token
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: INFLUXDB_ADDR
              value: "https://influxdb-influxdb2.influxdb.svc.cluster.local:8086"
            - name: INFLUXDB_SERVER_NAME
              value: "influxdb-influxdb2.influxdb.svc.cluster.local"
          volumeMounts:
            - name: vector-config
              mountPath: /etc/vector/
              readOnly: true
            - name: vault-issuer-ca
              mountPath: /etc/ssl/certs/
              readOnly: true
            - name: var-lib
              mountPath: /var/lib/vector
            - name: k8s-pod-logs
              mountPath: /var/log/pods
              readOnly: true
            - name: host-proc
              mountPath: /proc
              readOnly: true
            - name: host-sys
              mountPath: /sys
              readOnly: true
          resources:
            limits:
              cpu: "150m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: vector-config
          configMap:
            name: vector-config
        - name: vault-issuer-ca
          configMap:
            name: vault-issuer-ca
        - name: var-lib
          emptyDir: {}
        - name: k8s-pod-logs
          hostPath:
            path: /var/log/pods
            type: Directory
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory