apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vector
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow Vault to send StatsD metrics
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: vault
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vault
      ports:
        - port: 9000
          protocol: UDP
    # Allow other Vector instances to forward events
    - ports:
        - port: 8222
          protocol: TCP
  egress:
    # Allow writing data to InfluxDB
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: influxdb2  
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: influxdb
      ports:
        - port: 8086
          protocol: TCP
    # Allow requesting secrets from Vault via Vault Agent Injector
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: vault
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vault
      ports:
        - port: 8200
          protocol: TCP
    # Allow Kubernetes API server access for pod log metadata
    - to:
        - ipBlock:
            cidr: 192.168.8.0/24
      ports:
        - port: 6443
          protocol: TCP
    # Allow DNS resolution
    - ports:
        - port: 53
          protocol: UDP